INSERT INTO TB_UNIDADE (NOME, ENDERECO, STATUS) VALUES ('UNIDADE CENTRO', 'Rua da Assembléia 77', 'ATIVA');
INSERT INTO TB_UNIDADE (NOME, ENDERECO, STATUS) VALUES ('UNIDADE CENTRO', 'Rua da Carioca 100', 'ATIVA');
INSERT INTO TB_UNIDADE (NOME, ENDERECO, STATUS) VALUES ('UNIDADE TIJUCA', 'Rua Haddock Lobo 200', 'ATIVA');

INSERT INTO TB_TURMA (NOME, STATUS) VALUES ('JAVA', 'ATIVA');
INSERT INTO TB_TURMA (NOME, STATUS) VALUES ('ANGULAR 2+', 'ATIVA');
INSERT INTO TB_TURMA (NOME, STATUS) VALUES ('C#', 'ATIVA');

INSERT INTO TB_UNIDADE_TURMA (UNIDADE_ID, TURMA_ID) VALUES (1, 1); 
INSERT INTO TB_UNIDADE_TURMA (UNIDADE_ID, TURMA_ID) VALUES (1, 2); 

INSERT INTO TB_UNIDADE_TURMA (UNIDADE_ID, TURMA_ID) VALUES (2, 3); 

INSERT INTO TB_UNIDADE_TURMA (UNIDADE_ID, TURMA_ID) VALUES (3, 1); 
INSERT INTO TB_UNIDADE_TURMA (UNIDADE_ID, TURMA_ID) VALUES (3, 2); 
INSERT INTO TB_UNIDADE_TURMA (UNIDADE_ID, TURMA_ID) VALUES (3, 3); 

