-- MySQL Script generated by MySQL Workbench
-- Tue Jan 19 23:09:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_curso_preparatorio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_curso_preparatorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_curso_preparatorio` DEFAULT CHARACTER SET utf8 ;
USE `db_curso_preparatorio` ;

-- -----------------------------------------------------
-- Table `db_curso_preparatorio`.`tb_unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_curso_preparatorio`.`tb_unidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `endereco` VARCHAR(60) NOT NULL COMMENT 'Endereço não pode ser repetido.',
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_endereco_UK` (`nome` ASC, `endereco` ASC)  COMMENT 'O nome da unidade pode se repetir, desde que seja para endereços diferentes ex. \\nNome Cascadura end quintão\\nNome Cascadura end ana quintão',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_curso_preparatorio`.`tb_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_curso_preparatorio`.`tb_turma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_curso_preparatorio`.`tb_unidade_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_curso_preparatorio`.`tb_unidade_turma` (
  `unidade_id` INT NOT NULL,
  `turma_id` INT NOT NULL,
  PRIMARY KEY (`unidade_id`, `turma_id`),
  INDEX `fk_tb_unidade_turma_tb_turma_idx` (`turma_id` ASC),
  INDEX `fk_tb_unidade_turma_tb_unidade_idx` (`unidade_id` ASC),
  CONSTRAINT `fk_tb_unidade_turma_tb_unidade`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `db_curso_preparatorio`.`tb_unidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_unidade_turma_tb_turma`
    FOREIGN KEY (`turma_id`)
    REFERENCES `db_curso_preparatorio`.`tb_turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
